from pyspark.sql.types import StructType, StructField, StringType, IntegerType, ArrayType, FloatType

weather_schema = StructType([StructField('id', IntegerType(), True),
                     StructField('name', StringType(), True),
                     StructField('latitude', FloatType(), True),
                     StructField('longitude', FloatType(), True),
                     StructField('elevation', FloatType(), True),
                     StructField('feature_code', StringType(), True),
                     StructField('country_code', StringType(), True),
                     StructField('admin1_id', IntegerType(), True),
                     StructField('admin2_id', IntegerType(), True),
                     StructField('timezone', StringType(), True),
                     StructField('population', IntegerType(), True),
                     StructField('postcodes', ArrayType(StringType()), True),
                     StructField('country_id', IntegerType(), True),
                     StructField('country', StringType(), True),
                     StructField('admin1', StringType(), True),
                     StructField('admin2', StringType(), True),
                     StructField('generationtime_ms', IntegerType(), True),
                     StructField('utc_offset_seconds', IntegerType(), True),
                     StructField('timezone_abbreviation', StringType(), True),
                     StructField('hourly_units', StructType([StructField('time', StringType(), True),
                                                             StructField('temperature_2m', StringType(), True),
                                                             StructField('relative_humidity_2m', StringType(), True),
                                                             StructField('dew_point_2m', StringType(), True),
                                                             StructField('apparent_temperature', StringType(), True),
                                                             StructField('precipitation', StringType(), True),
                                                             StructField('weather_code', StringType(), True),
                                                             StructField('pressure_msl', StringType(), True),
                                                             StructField('surface_pressure', StringType(), True),
                                                             StructField('visibility', StringType(), True),
                                                             StructField('wind_speed_10m', StringType(), True),
                                                             StructField('wind_direction_10m', StringType(), True),
                                                             StructField('soil_temperature_0cm', StringType(), True),
                                                             StructField('soil_temperature_6cm', StringType(), True),
                                                             StructField('soil_moisture_0_to_1cm', StringType(), True),
                                                             StructField('soil_moisture_1_to_3cm', StringType(),
                                                                         True)]), True),
                     StructField('hourly', StructType([StructField('time', ArrayType(StringType()), True),
                                                       StructField('temperature_2m', ArrayType(FloatType()), True),
                                                       StructField('relative_humidity_2m', ArrayType(IntegerType()),
                                                                   True),
                                                       StructField('dew_point_2m', ArrayType(FloatType()), True),
                                                       StructField('apparent_temperature', ArrayType(FloatType()),
                                                                   True),
                                                       StructField('precipitation', ArrayType(FloatType()), True),
                                                       StructField('weather_code', ArrayType(IntegerType()), True),
                                                       StructField('pressure_msl', ArrayType(FloatType()), True),
                                                       StructField('surface_pressure', ArrayType(FloatType()), True),
                                                       StructField('visibility', ArrayType(FloatType()), True),
                                                       StructField('wind_speed_10m', ArrayType(FloatType()), True),
                                                       StructField('wind_direction_10m', ArrayType(FloatType()),
                                                                   True),
                                                       StructField('soil_temperature_0cm', ArrayType(FloatType()),
                                                                   True),
                                                       StructField('soil_temperature_6cm', ArrayType(FloatType()),
                                                                   True),
                                                       StructField('soil_moisture_0_to_1cm', ArrayType(FloatType()),
                                                                   True),
                                                       StructField('soil_moisture_1_to_3cm', ArrayType(FloatType()),
                                                                   True)]), True)])
zipped_columns = ["time", "temperature_2m", "relative_humidity_2m", "dew_point_2m", "apparent_temperature",
                  "precipitation", "weather_code", "pressure_msl", "surface_pressure", "visibility", "wind_speed_10m",
                  "wind_direction_10m", "soil_temperature_0cm", "soil_temperature_6cm", "soil_moisture_0_to_1cm",
                  "soil_moisture_1_to_3cm"]
